jwt.secret=B0wZV/FLoSNa3QYC8lIz0MMu0K02rPIBc0XXoL6K5d8=
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update